### ISSUE TITLE
Search broken by recent change to use topic ids

### ISSUE THREAD

**Issue by joe1chen** [julianlam/nodebb-plugin-solr#18]
It looks like search is broken due to a recent NodeBB change made to src/search.js on 1/7/15 (60f1b9679ad42731fd9782261989efb8f4717f76).  

In ```searchInPosts``` function
```
getMainPids(results.tids, next);
```
tries to get the main pids from the ```results.tids```, which is an empty array.

The old code would try to get the main pids from the tids, but would then merge in the ```results.pids```, so it just happened to work.

**Comment by joe1chen** [comment]
On closer look.. I think I may have had some invalid data left in my search index that was causing this to be broken.  Sorry for the false alarm.

**Comment by julianlam** [comment]
On the topic of indexing -- I hate how indexing takes bloody forever if you have a large dataset. Any thoughts on how we could improve the UX?

**Comment by joe1chen** [comment]
A couple of indexing improvements that could be applied:

1) Bulk indexing - https://www.hakkalabs.co/articles/took-cue-nasa-used-solr-reduce-indexing-time-14-hours-12-minutes

Not sure if the Solr js client supports bulk indexing, but the above article seemed to indicated that using Solr's native bulk indexer ```DataImportHandler``` could dramatically improve indexing speed.

2) Collection aliases - 

https://issues.apache.org/jira/browse/SOLR-4497
http://blog.cloudera.com/blog/2013/10/collection-aliasing-near-real-time-search-for-really-big-data/

The way this works is that when you want to re-index your entire dataset, you would create a collection alias for the new index.  The old data would continue to use the old index until your data is done indexing, then you would transparently swap in the new index in place of the old one, so there would be no downtime as far as the end-user is concerned.

I think Solr 4.2 is required for collection aliasing.

3) As far as UX ideas, a simple progress bar would work well.  You could get the total number of topics/posts to index, and then break them into batches to bulk index. When each batch is done, you can update the progress bar.
