### ISSUE TITLE
No search data for description_t shown

### ISSUE THREAD

**Issue by shady2k** [julianlam/nodebb-plugin-solr#20]
Why this plugin show only topic search data?
I see in Solr log, that it search for description_t and title_t. description_t returns 37 results, title_t - 0.
But user see nothing.

2447575 [qtp507584865-14] INFO org.apache.solr.core.SolrCore – [collection1] webapp=/solr path=/select params={start=0&q=дизайн&qf=description_t^1&wt=json&rows=500&defType=dismax} hits=37 status=0 QTime=1
2447575 [qtp507584865-16] INFO org.apache.solr.core.SolrCore – [collection1] webapp=/solr path=/select params={start=0&q=дизайн&qf=title_t^1&wt=json&rows=500&defType=dismax} hits=0 status=0 QTime=1

nodebb log:
9/2 12:42 [30014] - verbose: [plugin/solr] Search (topic) for "дизайн" returned 0 results
9/2 12:42 [30014] - verbose: [plugin/solr] Search (post) for "дизайн" returned 38 results

**Comment by julianlam** [comment]
What version are you using, and have you reindexed the data?

**Comment by shady2k** [comment]
Latest, 1.0.3. Yes, I flushed search index.

**Comment by shady2k** [comment]
Check now, yes, with socket available it works. But I want ajax...

**Comment by shady2k** [comment]
Thank you, fixed in version 1.0.4.
