### ISSUE TITLE
index uid/cid with posts/topics

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-solr#21]
adding them to solr seems easy not sure about querying.

```
var payload = {
    id: 'post:' + postData.pid,	// Just needs to be unique
    'pid_i': postData.pid,
    'cid_i': postData.cid,
    'uid_i`: postsData.uid                      
};
	
payload[Solr.config.contentField || 'description_t'] = postData.content;
Solr.add(payload);
```

core branch that has the changes https://github.com/NodeBB/NodeBB/tree/search-cid-uid

**Comment by julianlam** [comment]
@barisusakli It works, this is mergeable back into master except for a bug where topic move doesn't actually update the `cid_i` value correctly. Need to look into that tonight.

... or you can, lmk.

**Comment by julianlam** [comment]
Apparently Solr Query Syntax is **whitespace significant** :rage4:

**Comment by barisusakli** [comment]
`action:post.move` needs to be handled as well.

**Comment by julianlam** [comment]
Thanks :+1: will do that now
