### ISSUE TITLE
concat index error

### ISSUE THREAD

**Issue by martyalicante** [julianlam/nodebb-plugin-solr#23]
i got error indexing my database, it says , "cant concat topic id undefined" or something like, these, i don't have the error here but i will reproduce it if needed
it index all topics but seems like it tries to find topics numbers beyond my database range.
lets say if i have 12000 topics, it tries to index the topic with id 12001

**Comment by julianlam** [comment]
Stack trace would be helpful :smile:

**Comment by martyalicante** [comment]
I will try to get it :)
