### ISSUE TITLE
Crashing on v0.9.2

### ISSUE THREAD

**Issue by miranmirza** [julianlam/nodebb-plugin-solr#27]
I've just installed the plugin on my NodeBB v0.9.2 and tried to rebuild my search index. I got the following message in my log "warn: [deprecated] User.getMultipleUserFields is deprecated please use User.getUsersFields" and then "[cluster] Child Process (2819) has exited (code: null, signal: SIGKILL)
[cluster] Spinning up another process..."

**Comment by julianlam** [comment]
No crash here, it completes the reindex on v0.9.2 for me. Perhaps the crash is unrelated?
