### ISSUE TITLE
Duplicate items in search index

### ISSUE THREAD

**Issue by yackushevas** [julianlam/nodebb-plugin-solr#28]
I found a bug: add the topic -> it is added to the index -> edit the topic -> index added a new version of the message.

The result: in the index have two topic (old and new).

Temporary solution: manual rebuild search index

**Comment by julianlam** [comment]
Can't reproduce this one. When I create a topic and edit it, I see the existing entry changed, not a duplicate one made.

```
<result name="response" numFound="2" start="0">
	<doc>
		<str name="description_t">merhaba baris and andrew</str>
		<str name="id">post:72</str>
		<int name="pid_i">72</int>
		<int name="tid_i">24</int>
		<str name="title_t">Testing Solr indexing</str>
		<int name="uid_i">1</int>
	</doc>
	<doc>
		<int name="cid_i">1</int>
		<str name="id">topic:24</str>
		<int name="tid_i">24</int>
		<str name="title_t">Testing Solr indexing</str>
		<int name="uid_i">1</int>
	</doc>
</result>
```

**Comment by julianlam** [comment]
I did find a bug with the topic entry value not changing, so perhaps that's what you were referring to.

**Comment by yackushevas** [comment]
Yes, i not tested change topic entry - problem with the contents.

**Comment by julianlam** [comment]
Can't reproduce that one either -- the content is changed correctly, not duplicated.

Perhaps you need to update to the latest version of this plugin?

**Comment by yackushevas** [comment]
I have the latest version of the plugin and nodebb. I'll try to solve the problem on their own. Thank you.
