### ISSUE TITLE
After upgrading the plugin, nodebb could not connect to solr search engine.

### ISSUE THREAD

**Issue by Captain1** [julianlam/nodebb-plugin-solr#29]
How to adjust settings to connect to solr server? I have opened the inbound 8983 port in my server but with no luck.

**Comment by julianlam** [comment]
Sometimes solr listens on port 8080

**Comment by Captain1** [comment]
Doesn't work on port 8080 either, tried upgrading the forum from 1.0.0 to 1.0.2 and reload still shows failed to connect to solr server. (Do i have to install and deploy solr on server myself?)

**Comment by julianlam** [comment]
> (Do i have to install and deploy solr on server myself?)

Yes :smile:
