### ISSUE TITLE
Bug after tomcat update

### ISSUE THREAD

**Issue by Finch29** [julianlam/nodebb-plugin-solr#32]
hi, after tomcat7 update, the plugin doesn't do a good request ... this is my error logs : 

https://i.imgur.com/Xh0w5Vw.png

> 19/12 01:39 [16241] - [31merror[39m: [plugins] filter:search.query,  
Request URL: http://127.0.0.1:8983/solr/select?q=&defType=edismax&qf=description_t%5E1&start=0&rows=500&wt=json
Request method: GET
Status code: 400 - Bad Request
Request headers: 
accept: application/json; charset=utf-8
host: 127.0.0.1:8983
Response headers: 
server: Apache-Coyote/1.1
transfer-encoding: chunked
date: Mon, 19 Dec 2016 00:39:57 GMT
connection: close
19/12 01:39 [16241] - [31merror[39m: /search
 SolrError: 
Request URL: http://127.0.0.1:8983/solr/select?q=&defType=edismax&qf=description_t%5E1&start=0&rows=500&wt=json
Request method: GET
Status code: 400 - Bad Request
Request headers: 
accept: application/json; charset=utf-8
host: 127.0.0.1:8983
Response headers: 
server: Apache-Coyote/1.1
transfer-encoding: chunked
date: Mon, 19 Dec 2016 00:39:57 GMT
connection: close
    at IncomingMessage.<anonymous> (/home/forum/node_modules/solr-client/lib/solr.js:779:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by julianlam** [comment]
@Finch29 -- thanks, is it possible for you to downgrade in the meantime?

**Comment by Finch29** [comment]
tomorrow i try to do this but i'm not sure if i can do this :s

**Comment by Finch29** [comment]
Same error when i try to downgrade Tomcat7 ... :'(

**Comment by Finch29** [comment]
Any news ? :s

**Comment by Finch29** [comment]
Any news? 😕

**Comment by Finch29** [comment]
What's your solr version ? i've 3.6.2

**Comment by Finch29** [comment]
it's work fine if i go on " x.x.x.x:8983 " and " x.x.x.x:8983/solr/admin " too. When i try " x.x.x.x/solr/select?q=&defType=edismax&qf=description_t%5E1&start=0&rows=500&wt=json " he dosen't return a 400 bad request ... 

https://i.imgur.com/mKvAZHk.png

**Comment by Finch29** [comment]
Any news ? :s

**Comment by Finch29** [comment]
I've install Jetty instead of Tomcat and it's work !
