### ISSUE TITLE
push latest commit to npm

### ISSUE THREAD

**Issue by phit** [julianlam/nodebb-plugin-solr#35]
Since the 1.5.X update I have to run "Rebuild Search Index" manually in the admin panel for new posts and topics to show up in the search. 

Currently using 3.0.1, which latest on npm and it doesn't seem to include this commit https://github.com/julianlam/nodebb-plugin-solr/commit/38008330d79310868a22f3e8e90272964b14bef8 that possibly fixes it?

**Comment by julianlam** [comment]
Yes, oversight on my part, v4.0.0 of the Solr plugin is published now.

**Comment by phit** [comment]
thanks!
