### ISSUE TITLE
Rebuilding index on forums with a lot of topics and posts

### ISSUE THREAD

**Issue by Dravere** [julianlam/nodebb-plugin-solr#36]
So I tried this plugin to index a forum with over 2 million posts. Two things happened and no post was ever indexed.

* After clicking on `Rebuild Index` a message immediately appears, saying "Search index rebuilt". Which seems very unlikely with 2 million posts.
* After some time NodeBB got killed by the Linux OOM killer. It used up every available bit of memory.

Looking at the code I think the first one could be a racing condition? It makes a HTTP POST to the server to start rebuilding the index and immediately afterwards does a HTTP GET to get the current status of the process. Could it be possible that it hasn't started yet and thus is displaying a success?

In regards to the second problem, I think this plugin is trying to keep all 2 million posts in memory before submitting them to Solr. At least that is what I get from the code. For every function indexing something there is a if-condition at the end before indexing to check if a callback is given. When a callback is available it returns the prepared payloads instead of submitting them to Solr. And thus collects all payloads until it has every payload needed to rebuild the index. This includes all indexable user data, all topic titles and metadata and all post contents and metadata.

Is this correct? And if so why is this plugin keeping all this data in memory before submitting to Solr? Is there an easy way around it?

**Comment by Dravere** [comment]
So I tried to go the easy route on that one and just threw hopefully enough memory at it. Started it back up and the Javascript Engine crashed, because it ran out of memory. I watched the entire process. The machine still had about 4 GB of memory available. So it seems it was at the end limited by the Javascript engine.

```
<--- Last few GCs --->

  287075 ms: Mark-sweep 1258.5 (1435.6) -> 1256.7 (1435.6) MB, 434.6 / 0.0 ms [allocation failure] [GC in old space requested].
  287509 ms: Mark-sweep 1256.7 (1435.6) -> 1256.7 (1435.6) MB, 433.8 / 0.0 ms [allocation failure] [GC in old space requested].
  287942 ms: Mark-sweep 1256.7 (1435.6) -> 1266.8 (1404.6) MB, 433.0 / 0.0 ms [last resort gc].
  288372 ms: Mark-sweep 1266.8 (1404.6) -> 1278.0 (1404.6) MB, 430.2 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3129fc6cf781 <JS Object>
    1: set [native collection.js:~252] [pc=0x2552cff9967b] (this=0x470949703e1 <a Map with map 0x346af9c09c11>,r=0x1011d4eefce1 <String[12]: post:1408515>,z=0x38b90965c959 <a Node with map 0x35dba95102d9>)
    2: set [/data/node_modules/lru-cache/index.js:~296] [pc=0x2552cff9c682] (this=0xb8e0f5ad2f9 <a LRUCache with map 0x35dba959f439>,key=0x1011d4eefce1 <String[12]: post:1408515>,value=0x18d5...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: 0x109f0ac [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Rehash(v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/local/bin/node]
 8: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::EnsureGrowable(v8::internal::Handle<v8::internal::OrderedHashMap>) [/usr/local/bin/node]
 9: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x2552ce0092a7
```

This code sadly doesn't work with bigger forums.

**Comment by julianlam** [comment]
Hi @Dravere -- that is likely the case... on the js side, we're indexing posts but don't actively push anything to Solr until the very end, so the index is being build on the js side.

Looks like this could be potentially resolved with pushing to Solr periodically, although I'm not sure how much of a rewrite it would involve :\

**Comment by Dravere** [comment]
I'm already at it. Didn't have much time at the moment, but either this or next week I might provide a pull request as suggestion for a solution. For both problems.

**Comment by Dravere** [comment]
Since both pull requests were merged, I'll close this issue.
