### ISSUE TITLE
Reducing amount of warnings

### ISSUE THREAD

**Issue by Dravere** [julianlam/nodebb-plugin-solr#47]
Looking at the code in WebStorm is kind of ridiculous in regards to the amount of warnings. At least changing from `var` to `let` would already be a huge improvements. And since the minimum requirement for NodeBB is now NodeJS 6 this shouldn't be a problem.

**Comment by julianlam** [comment]
:+1: We could introduce the same code auditing tools we use in NodeBB core... I believe it's eslint?
