### ISSUE TITLE
Occur a error while Searching

### ISSUE THREAD

**Issue by greenhat616** [julianlam/nodebb-plugin-solr#52]
The log is:
```
2018-12-02T00:43:20.808Z [20599] - [31merror[39m: /api/search
SolrError
    at IncomingMessage.<anonymous> (/home/ubuntu/nodebb/node_modules/solr-client/lib/solr.js:991:19)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Some tracks might lose. is it a incompatible problem?

Node version: 10.14.0
Yarn version: 1.12.3
NPM version: 6.4.1
JRE version: 1.8.0_191
OS release: Ubuntu 18.04.1
Tomcat info:
```
Using CATALINA_BASE:   /usr/share/tomcat8
Using CATALINA_HOME:   /usr/share/tomcat8
Using CATALINA_TMPDIR: /usr/share/tomcat8/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar
Server version: Apache Tomcat/8.5.30 (Ubuntu)
Server built:   Aug 13 2018 20:23:56 UTC
Server number:  8.5.30.0
OS Name:        Linux
OS Version:     4.15.0-39-generic
Architecture:   amd64
JVM Version:    1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12
JVM Vendor:     Oracle Corporation
```
Solr Specification Version: 3.6.2.2018.01.14.13.32.32
Solr Implementation Version:   3.6.2 debian - buildd - 2018-01-14 13:32:32

NodeBB Version: v1.11.0
Plugin Version: Current.

Community URL: https://community.nodebb-cn.org

Thanks for your fixing.

**Comment by Dravere** [comment]
Debian seems to have a very old Solr distribution in its repository. This plugin is tested and developed against Solr 7.x.

**Comment by greenhat616** [comment]
> Debian seems to have a very old Solr distribution in its repository. This plugin is tested and developed against Solr 7.x.

![image](https://user-images.githubusercontent.com/41122242/49338774-bf819000-f661-11e8-8e01-6e6aa9a6bcb3.png)

I had updated to v7.5. After Reconfiguring, rebuilding, restarting, it occured the error yet.

**Comment by Dravere** [comment]
The only thing I could think of at this moment, is that you have it configured like that in the plugin settings. Make sure that in the ACP the field for description is set to `description_t` without the `^1`.

**Comment by greenhat616** [comment]
@Dravere Ok, i know. Solr is not work well in Tomcat now. so, i use docker to run solr. Now, everything seems well.
